### PR TITLE
support the Python-Eve generic sorting syntax

### PR DESCRIPTION
**Pull request by goneri**
Add support of the python Eve sorting syntax:

    $ curl -i http://eve-demo.herokuapp.com/people?sort=city,-lastname

### CODE REVIEW

**Comment by amleczko** [comment]
@goneri can you add a coverage test?

**Comment by goneri** [comment]
Here it is :)

**Comment by goneri** [comment]
Oopps, I forgot to `git add` the unit-test file ...

**Comment by amleczko** [comment]
Thx!

**Pull request merged**
