### PR TITLE
ValidatorSQL class doesn't handle/pass allow_unknown

### PR DESCRIPTION
**Pull request by lingfish**
As per https://github.com/RedTurtle/eve-sqlalchemy/issues/70.

The test isn't spectacular, but you wanted a small one ;)

### CODE REVIEW

**Comment by amleczko** [comment]
travis tests are failing?

**Comment by lingfish** [comment]
There we go -- mine is fixed, the others aren't my code.

**Comment by goneri** [comment]
It's a constraint failure:
```
self = <sqlalchemy.dialects.sqlite.pysqlite.SQLiteDialect_pysqlite object at 0x7f1082107a90>
cursor = <sqlite3.Cursor object at 0x7f1082489650>
statement = 'INSERT INTO people (_created, _updated, _etag, firstname, lastname, prog, born, title) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'
parameters = ('2015-10-01 12:01:30.149928', '2015-10-01 12:01:30.149928', 'da39a3ee5e6b4b0d3255bfef95601890afd80709', 'Kafgpi', 'Mdmokn', 59, ...)
context = <sqlalchemy.dialects.sqlite.base.SQLiteExecutionContext object at 0x7f1083242950>

    def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: people.firstname [SQL: u'INSERT INTO people (_created, _updated, _etag, firstname, lastname, prog, born, title) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('2015-10-01 12:01:30.149928', '2015-10-01 12:01:30.149928', 'da39a3ee5e6b4b0d3255bfef95601890afd80709', 'Kafgpi', 'Mdmokn', 59, None, None)]
```
It's funny it just appends with this patch.

**Comment by goneri** [comment]
Hi,
I pushed a fix for the unit-test and took the liberty to rebase the two patches: https://github.com/goneri/eve-sqlalchemy/tree/bug-70

**Comment by lingfish** [comment]
Nice find, thanks.

**Comment by lingfish** [comment]
Nice.

**Pull request merged**
