### PR TITLE
New constructor that pass a reference to eve when initializing the auth object 

### PR DESCRIPTION
**Pull request by joystein**
Otherwise have to (as far as i can see) do:

```python
app = Eve(
    settings=SETTINGS_PATH,
    validator=ValidatorSQL,
    data=SQL,
    auth=TokenAuth,
)


# NOTE: This is a bit convoluted. TokenAuth needs reference to db.
TokenAuth.app = app
```

### CODE REVIEW

**Comment by goneri** [comment]
Thanks for the PR @joystein. I'm not the maintainer of this repository but I've some few comments.

Commit 21995c25fc207bb0896dfc6a2c844b34c3d5cfb3 is just a fix for the previous one. You should just merge it in the previous commit.
Your branch commit a merge commit (e6611a6), you should rebase your branch against upstream master instead of using merge.

The pep8 failure can easily be fixed. Here again, adjust the existing commit (e.g: git commit --amend).
Also, a new unit-test would be a plus.

**Comment by joystein** [comment]
Thanks for reviewing @goneri. How does it look now?

**Comment by amleczko** [comment]
I don't have problems with accessing db from my `TokenAuth`. Can you show your implementation of it?

**Comment by joystein** [comment]
```python
from eve.auth import TokenAuth

class TokenAuth(TokenAuth):
    
    def __init__(self, app):
        self.app = app
    
    def check_auth(self, token, allowed_roles, resources, method):
        
        # Verify if the token is valid
        username = User.verify_auth_token(token)
        user = self.app.data.driver.session.query(User).filter_by(username=username).one()
        self.set_request_auth_value(user.id)
        
        if username:
            return True
        else:
            return False
```

**Comment by amleczko** [comment]
Well it's part of the documentation - http://eve-sqlalchemy.readthedocs.org/en/stable/tutorial.html#authentication-example

**Comment by joystein** [comment]
There you have `app` available because its instantiated in the same file as TokenAuth is defined, right?. I have moved TokenAuth to a separate `auth` module file as that way of organizing files made more sense in my project.

The approach is the same as for `data` and `media` parameters in the eve app constructor:
https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L144
https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L148

**Comment by amleczko** [comment]
Well you can use:
```python
from flask import current_app as app
``` 
Not that I'm a big fan of this approach - but I'm also using it in one of my projects.

**Comment by joystein** [comment]
Right. So this is the flask way of doing things then. I'm new to flask so please excuse my ignorance.

Ideally one would rather have changed `auth()` to `auth(self)` in  https://github.com/nicolaiarocci/eve/blob/develop/eve/flaskapp.py#L152 to achieve the same.

**Pull request closed without merging**
