### PR TITLE
embedded table: use DOMAIN to look up the resource fields

### PR DESCRIPTION
**Pull request by goneri**
This patch resolve two issues:
- it's now possible to have a resource field that is a relation to
  another relation, even if the name doesn't match. For example,
  product_stable and product_devel are two one-to-one field with a
  relationship to product
- when we associate a foreign resource, we skip the `foreign_resource`
  field to avoid endless loop. For example, a any-to-one relation called
  `foo` with an associate to `bar` that we pull with embedded.
  `bar` has got a `foo_collection` with a link to `foo`. Previously, the
  `foo_collection` filed was automatically added in the list of field of `bar`.
  This was enough to create an endless loop in `lookup_foreign_resource`.

### CODE REVIEW

**Comment by kiniou** [comment]
:+1: Those changes looks good to me but i think it might need some other test cases.

**Comment by amleczko** [comment]
I like this PR, but it looks backward incompatible. My suggestion:
 * update documentation about it
 * add more tests
If you want I can add tests if you update docs :)

**Comment by goneri** [comment]
Hi @amleczko and @kiniou 

I refreshed the patch:
- it comes with an `embedded` section in the documentation
- a better (complet?) coverage.

**Comment by goneri** [comment]
@amleczko @kiniou is this PR fine for you now?

**Comment by amleczko** [comment]
Yes it looks pretty decent.
I will check it with one of my live projects and eventually write more test cases (I will keep you updated).

**Comment by goneri** [comment]
hi @amleczko,

Do you have some feedback regarding this PR?

**Comment by goneri** [comment]
I may have a better fix. I close the PR for the moment.

**Pull request closed without merging**
